using System.Text;
using NJsonSchema;

namespace CodeAlta.Acp.Generator;

internal static class AcpMethodEmitter
{
    public static string EmitClientMethods(
        IReadOnlyList<TypeDef> defs,
        AcpMethodMap methodMap,
        string rootNamespace)
    {
        ArgumentNullException.ThrowIfNull(defs);
        ArgumentNullException.ThrowIfNull(methodMap);
        ArgumentNullException.ThrowIfNull(rootNamespace);

        var entries = BuildMethodEntries(defs, methodMap, rootNamespace);
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {rootNamespace};");
        builder.AppendLine();
        builder.AppendLine("public sealed partial class AcpClient");
        builder.AppendLine("{");

        foreach (var entry in entries.Where(static x => x.Side == "agent").OrderBy(static x => x.SymbolName, StringComparer.Ordinal))
        {
            builder.AppendLine("    /// <summary>");
            builder.Append("    /// Sends the ACP `").Append(entry.MethodName).AppendLine("` call.");
            builder.AppendLine("    /// </summary>");
            builder.Append("    public ");
            if (entry.ResponseTypeName is null)
            {
                builder.Append("Task ");
            }
            else
            {
                builder.Append("Task<").Append(entry.ResponseTypeName).Append("> ");
            }

            builder.Append(entry.SymbolName).AppendLine("Async(");
            builder.Append("        ").Append(entry.RequestTypeName).AppendLine(" parameters,");
            builder.AppendLine("        CancellationToken cancellationToken = default)");
            builder.AppendLine("    {");
            builder.AppendLine("        ArgumentNullException.ThrowIfNull(parameters);");
            if (entry.ResponseTypeName is null)
            {
                builder.Append("        return _transport.SendNotificationAsync(\"")
                    .Append(entry.MethodName)
                    .AppendLine("\", parameters, cancellationToken);");
            }
            else
            {
                builder.Append("        return _transport.SendRequestAsync<")
                    .Append(entry.RequestTypeName)
                    .Append(", ")
                    .Append(entry.ResponseTypeName)
                    .Append(">(\"")
                    .Append(entry.MethodName)
                    .AppendLine("\", parameters, cancellationToken);");
            }

            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    public static string EmitMetadataPartial(
        string rootNamespace,
        AcpSchemaSourceInfo sourceInfo,
        AcpSurface surface,
        int methodMapVersion)
    {
        ArgumentNullException.ThrowIfNull(rootNamespace);
        ArgumentNullException.ThrowIfNull(sourceInfo);

        var generatedAtUtc = DateTimeOffset.UtcNow;
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine();
        builder.AppendLine($"namespace {rootNamespace};");
        builder.AppendLine();
        builder.AppendLine("public sealed partial class AcpClient");
        builder.AppendLine("{");
        builder.Append("    public const string CompiledAgainstSchemaSourceKind = \"")
            .Append(Escape(sourceInfo.SourceKind))
            .AppendLine("\";");
        builder.Append("    public const string CompiledAgainstSchemaSource = \"")
            .Append(Escape(sourceInfo.SourceDisplayName))
            .AppendLine("\";");
        builder.Append("    public const string CompiledAgainstRepository = \"")
            .Append(Escape(sourceInfo.RepositoryUrl))
            .AppendLine("\";");
        builder.Append("    public const string CompiledAgainstSurface = \"")
            .Append(surface == AcpSurface.Stable ? "stable" : "unstable")
            .AppendLine("\";");
        builder.Append("    public const string CompiledAgainstSchemaPath = \"")
            .Append(Escape(sourceInfo.SchemaPath))
            .AppendLine("\";");
        builder.Append("    public const string CompiledAgainstGitRef = \"")
            .Append(Escape(sourceInfo.GitRef ?? string.Empty))
            .AppendLine("\";");
        builder.Append("    public static DateTimeOffset CompiledAtUtc { get; } = DateTimeOffset.Parse(\"")
            .Append(generatedAtUtc.ToString("O"))
            .AppendLine("\", null, System.Globalization.DateTimeStyles.RoundtripKind);");
        builder.Append("    public const int CompiledAgainstMethodMapVersion = ")
            .Append(methodMapVersion.ToString(System.Globalization.CultureInfo.InvariantCulture))
            .AppendLine(";");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static List<AcpMethodEntry> BuildMethodEntries(
        IReadOnlyList<TypeDef> defs,
        AcpMethodMap methodMap,
        string rootNamespace)
    {
        var byMethod = new Dictionary<(string Method, string Side), AcpMethodEntry>();
        foreach (var def in defs)
        {
            var schema = SchemaWalker.Resolve(def.Schema);
            var methodName = GetExtensionDataString(schema, "x-method");
            var side = GetExtensionDataString(schema, "x-side");
            if (methodName is null || side is null)
            {
                continue;
            }

            var key = (methodName, side);
            if (!byMethod.TryGetValue(key, out var entry))
            {
                entry = new AcpMethodEntry
                {
                    MethodName = methodName,
                    Side = side,
                    SymbolName = ResolveMethodSymbol(methodMap, methodName),
                };
                byMethod[key] = entry;
            }

            var typeName = def.CsNamespace == rootNamespace
                ? def.Name
                : $"{def.CsNamespace}.{def.Name}";

            if (def.Name.EndsWith("Request", StringComparison.Ordinal) ||
                def.Name.EndsWith("Notification", StringComparison.Ordinal))
            {
                entry.RequestTypeName = typeName;
            }
            else if (def.Name.EndsWith("Response", StringComparison.Ordinal))
            {
                entry.ResponseTypeName = typeName;
            }
        }

        return byMethod.Values
            .Where(static entry => entry.RequestTypeName is not null)
            .ToList()!;
    }

    private static string ResolveMethodSymbol(AcpMethodMap methodMap, string methodName)
    {
        foreach (var pair in methodMap.AgentMethods)
        {
            if (string.Equals(pair.Value, methodName, StringComparison.Ordinal))
            {
                return SchemaWalker.ToPascalCase(pair.Key);
            }
        }

        foreach (var pair in methodMap.ClientMethods)
        {
            if (string.Equals(pair.Value, methodName, StringComparison.Ordinal))
            {
                return SchemaWalker.ToPascalCase(pair.Key);
            }
        }

        return SchemaWalker.ToPascalCase(methodName.Replace("/", "_", StringComparison.Ordinal));
    }

    private static string? GetExtensionDataString(JsonSchema schema, string key)
    {
        if (schema.ExtensionData is null || !schema.ExtensionData.TryGetValue(key, out var value) || value is null)
        {
            return null;
        }

        return value switch
        {
            string text => text,
            _ => value.ToString(),
        };
    }

    private static string Escape(string value)
    {
        return value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal);
    }

    private sealed class AcpMethodEntry
    {
        public required string MethodName { get; init; }

        public required string Side { get; init; }

        public required string SymbolName { get; init; }

        public string? RequestTypeName { get; set; }

        public string? ResponseTypeName { get; set; }
    }
}
